/**
 * Keyboard driver: Keyboard driver for the OS has only  one function,
 * that is to get the input from the keyboard.
 *
 * Presently, the keyboard driver is not capable of handling meta keys like capslock, numlock, etc.
 * but it can handle ctrl, alt, shift, etc.
 *
*/

#ifndef KEYBOARD_DRIVER_H
#define KEYBOARD_DRIVER_H

#include <stdint.h>
#include <stdbool.h>

#include "core/global.h"
#include "core/memory.h"


struct keyboard_input {
    uint8_t primary_input;
    uint8_t secondary_input;
} *keyboard_input;

void keyboard_input_init(struct keyboard_input* input) {
    input->primary_input = 0;
    input->secondary_input = 0;
}

void keyboard_input_set(struct keyboard_input* input, uint8_t primary_input, uint8_t secondary_input) {
    input->primary_input = primary_input;
    input->secondary_input = secondary_input;
}

/**
 * \brief Initializes keyboard
*/
void keyboard_init() {
    memory_set(memory + IO_KEYBOARD_START, IO_KEYBOARD_SIZE, 0);
    int start = IO_KEYBOARD_START;
    int end = IO_KEYBOARD_START + IO_KEYBOARD_SIZE;
    for (int i = start;i < end;i++) {
        mwrite('\0', i);
    }
}

struct keyboard_input keyboard_get_input() {
    uint8_t second_input = 0;
    uint8_t input = 0;
    bool can_break = false;

    keyboard_input_init(keyboard_input);

    while (true) {
        can_break = false;

        char f = mread_char(IO_KEYBOARD_START);
        if (f != 0) {
            input = f;
            mwrite(0, IO_KEYBOARD_START);
            can_break = true;

            // removed every logic for meta keys because 
            // i highly doubt that it will work due to continuous key press
            // generated by the keyboard

            if (can_break) break;
        }
    }

    keyboard_input_set(keyboard_input, input, second_input);
    return *keyboard_input;
}

struct keyboard_input manipulate_input(struct keyboard_input input) {
    struct keyboard_input out;

    out.primary_input = input.primary_input;
    out.secondary_input = input.secondary_input;

    // todo: manipulate the input here

    return out;
}

char* convert_keyinput_to_string(struct keyboard_input input) {
    char out[4];

    switch (input.primary_input) {
    case CTRL_CODE_ENTER: {
        // ENTR
        out[0] = 'E';
        out[1] = 'N';
        out[2] = 'T';
        out[3] = 'R';
    }

    case CTRL_CODE_ALT: {
        // ALT
        out[0] = 'A';
        out[1] = 'L';
        out[2] = 'T';
        out[3] = '\0';
    }

    case CTRL_CODE_SHIFT: {
        // SHFT
        out[0] = 'S';
        out[1] = 'H';
        out[2] = 'F';
        out[3] = 'T';
    }

    default: {
        out[0] = input.primary_input;
        out[1] = '\0';
    }
    }

    return out;
}

bool isEscape(struct keyboard_input input) {
    return input.primary_input == 0x1B;
}

#endif // KEYBOARD_DRIVER_H