name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.2
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
    - name: Build
      run: |
        make icmake
    - name: Run
      run: |
        make execute
